services:
  postgresql:
    image: postgres:12.20-alpine3.20
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=mental_instability_bot
      - POSTGRES_USER=mental_instability_bot
      - POSTGRES_PASSWORD=CHANGEMEPLEASE

volumes:
  postgres-data:
